# Generated by Django 5.2.12 on 2026-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('980', 'UAH'), ('840', 'USD'), ('978', 'EUR'), ('826', 'GBP'), ('392', 'JPY'), ('756', 'CHF'), ('156', 'CNY'), ('643', 'RUB'), ('784', 'AED'), ('971', 'AFN'), ('008', 'ALL'), ('051', 'AMD'), ('973', 'AOA'), ('032', 'ARS'), ('036', 'AUD'), ('944', 'AZN')], max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
